pragma Style_Checks (Off);

--  Copyright (c) 2010 - 2018, Nordic Semiconductor ASA
--
--  All rights reserved.
--
--  Redistribution and use in source and binary forms, with or without
--  modification, are permitted provided that the following conditions are met:
--
--  1. Redistributions of source code must retain the above copyright notice,
--  this list of conditions and the following disclaimer.
--
--  2. Redistributions in binary form, except as embedded into a Nordic
--  Semiconductor ASA integrated circuit in a product or a software update
--  for such product, must reproduce the above copyright notice, this list
--  of conditions and the following disclaimer in the documentation and/or
--  other materials provided with the distribution.
--
--  3. Neither the name of Nordic Semiconductor ASA nor the names of its
--  contributors may be used to endorse or promote products derived from
--  this software without specific prior written permission.
--
--  4. This software, with or without modification, must only be used with a
--  Nordic Semiconductor ASA integrated circuit.
--
--  5. Any software provided in binary form under this license must not be
--  reverse engineered, decompiled, modified and/or disassembled.
--
--  THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY
--  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
--  WARRANTIES OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A
--  PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR
--  ASA OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
--  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
--  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
--  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
--  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
--  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
--  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--

--  This spec has been automatically generated from nrf52840.svd

pragma Restrictions (No_Elaboration_Code);

with System;

package NRF52840.EGU is
   pragma Preelaborate;

   ---------------
   -- Registers --
   ---------------

   subtype TASKS_TRIGGER_TASKS_TRIGGER_Field is NRF52840.Bit;

   --  Description collection[n]: Trigger n for triggering the corresponding
   --  TRIGGERED[n] event
   type TASKS_TRIGGER_Register is record
      --  Write-only.
      TASKS_TRIGGER : TASKS_TRIGGER_TASKS_TRIGGER_Field := 16#0#;
      --  unspecified
      Reserved_1_31 : NRF52840.UInt31 := 16#0#;
   end record
     with Object_Size => 32, Bit_Order => System.Low_Order_First;

   for TASKS_TRIGGER_Register use record
      TASKS_TRIGGER at 0 range 0 .. 0;
      Reserved_1_31 at 0 range 1 .. 31;
   end record;

   subtype EVENTS_TRIGGERED_EVENTS_TRIGGERED_Field is NRF52840.Bit;

   --  Description collection[n]: Event number n generated by triggering the
   --  corresponding TRIGGER[n] task
   type EVENTS_TRIGGERED_Register is record
      EVENTS_TRIGGERED : EVENTS_TRIGGERED_EVENTS_TRIGGERED_Field := 16#0#;
      --  unspecified
      Reserved_1_31    : NRF52840.UInt31 := 16#0#;
   end record
     with Object_Size => 32, Bit_Order => System.Low_Order_First;

   for EVENTS_TRIGGERED_Register use record
      EVENTS_TRIGGERED at 0 range 0 .. 0;
      Reserved_1_31    at 0 range 1 .. 31;
   end record;

   --  Enable or disable interrupt for TRIGGERED[0] event
   type INTEN_TRIGGERED0_Field is
     (--  Disable
      Disabled,
      --  Enable
      Enabled)
     with Size => 1;
   for INTEN_TRIGGERED0_Field use
     (Disabled => 0,
      Enabled => 1);

   --  INTEN_TRIGGERED array
   type INTEN_TRIGGERED_Field_Array is array (0 .. 15)
     of INTEN_TRIGGERED0_Field
     with Component_Size => 1, Size => 16;

   --  Type definition for INTEN_TRIGGERED
   type INTEN_TRIGGERED_Field
     (As_Array : Boolean := False)
   is record
      case As_Array is
         when False =>
            --  TRIGGERED as a value
            Val : NRF52840.UInt16;
         when True =>
            --  TRIGGERED as an array
            Arr : INTEN_TRIGGERED_Field_Array;
      end case;
   end record
     with Unchecked_Union, Size => 16;

   for INTEN_TRIGGERED_Field use record
      Val at 0 range 0 .. 15;
      Arr at 0 range 0 .. 15;
   end record;

   --  Enable or disable interrupt
   type INTEN_Register is record
      --  Enable or disable interrupt for TRIGGERED[0] event
      TRIGGERED      : INTEN_TRIGGERED_Field :=
                        (As_Array => False, Val => 16#0#);
      --  unspecified
      Reserved_16_31 : NRF52840.UInt16 := 16#0#;
   end record
     with Object_Size => 32, Bit_Order => System.Low_Order_First;

   for INTEN_Register use record
      TRIGGERED      at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   --  Write '1' to enable interrupt for TRIGGERED[0] event
   type INTENSET_TRIGGERED0_Field is
     (--  Read: Disabled
      Disabled,
      --  Read: Enabled
      Enabled)
     with Size => 1;
   for INTENSET_TRIGGERED0_Field use
     (Disabled => 0,
      Enabled => 1);

   --  Write '1' to enable interrupt for TRIGGERED[0] event
   type INTENSET_TRIGGERED0_Field_1 is
     (--  Reset value for the field
      INTENSET_TRIGGERED0_Field_Reset,
      --  Enable
      Set)
     with Size => 1;
   for INTENSET_TRIGGERED0_Field_1 use
     (INTENSET_TRIGGERED0_Field_Reset => 0,
      Set => 1);

   --  INTENSET_TRIGGERED array
   type INTENSET_TRIGGERED_Field_Array is array (0 .. 15)
     of INTENSET_TRIGGERED0_Field_1
     with Component_Size => 1, Size => 16;

   --  Type definition for INTENSET_TRIGGERED
   type INTENSET_TRIGGERED_Field
     (As_Array : Boolean := False)
   is record
      case As_Array is
         when False =>
            --  TRIGGERED as a value
            Val : NRF52840.UInt16;
         when True =>
            --  TRIGGERED as an array
            Arr : INTENSET_TRIGGERED_Field_Array;
      end case;
   end record
     with Unchecked_Union, Size => 16;

   for INTENSET_TRIGGERED_Field use record
      Val at 0 range 0 .. 15;
      Arr at 0 range 0 .. 15;
   end record;

   --  Enable interrupt
   type INTENSET_Register is record
      --  Write '1' to enable interrupt for TRIGGERED[0] event
      TRIGGERED      : INTENSET_TRIGGERED_Field :=
                        (As_Array => False, Val => 16#0#);
      --  unspecified
      Reserved_16_31 : NRF52840.UInt16 := 16#0#;
   end record
     with Object_Size => 32, Bit_Order => System.Low_Order_First;

   for INTENSET_Register use record
      TRIGGERED      at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   --  Write '1' to disable interrupt for TRIGGERED[0] event
   type INTENCLR_TRIGGERED0_Field is
     (--  Read: Disabled
      Disabled,
      --  Read: Enabled
      Enabled)
     with Size => 1;
   for INTENCLR_TRIGGERED0_Field use
     (Disabled => 0,
      Enabled => 1);

   --  Write '1' to disable interrupt for TRIGGERED[0] event
   type INTENCLR_TRIGGERED0_Field_1 is
     (--  Reset value for the field
      INTENCLR_TRIGGERED0_Field_Reset,
      --  Disable
      Clear)
     with Size => 1;
   for INTENCLR_TRIGGERED0_Field_1 use
     (INTENCLR_TRIGGERED0_Field_Reset => 0,
      Clear => 1);

   --  INTENCLR_TRIGGERED array
   type INTENCLR_TRIGGERED_Field_Array is array (0 .. 15)
     of INTENCLR_TRIGGERED0_Field_1
     with Component_Size => 1, Size => 16;

   --  Type definition for INTENCLR_TRIGGERED
   type INTENCLR_TRIGGERED_Field
     (As_Array : Boolean := False)
   is record
      case As_Array is
         when False =>
            --  TRIGGERED as a value
            Val : NRF52840.UInt16;
         when True =>
            --  TRIGGERED as an array
            Arr : INTENCLR_TRIGGERED_Field_Array;
      end case;
   end record
     with Unchecked_Union, Size => 16;

   for INTENCLR_TRIGGERED_Field use record
      Val at 0 range 0 .. 15;
      Arr at 0 range 0 .. 15;
   end record;

   --  Disable interrupt
   type INTENCLR_Register is record
      --  Write '1' to disable interrupt for TRIGGERED[0] event
      TRIGGERED      : INTENCLR_TRIGGERED_Field :=
                        (As_Array => False, Val => 16#0#);
      --  unspecified
      Reserved_16_31 : NRF52840.UInt16 := 16#0#;
   end record
     with Object_Size => 32, Bit_Order => System.Low_Order_First;

   for INTENCLR_Register use record
      TRIGGERED      at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   -----------------
   -- Peripherals --
   -----------------

   --  Event Generator Unit 0
   type EGU_Peripheral is record
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_0     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_0);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_1     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_1);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_2     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_2);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_3     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_3);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_4     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_4);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_5     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_5);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_6     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_6);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_7     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_7);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_8     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_8);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_9     : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_9);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_10    : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_10);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_11    : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_11);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_12    : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_12);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_13    : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_13);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_14    : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_14);
      --  Description collection[n]: Trigger n for triggering the corresponding
      --  TRIGGERED[n] event
      TASKS_TRIGGER_15    : aliased TASKS_TRIGGER_Register;
      pragma Volatile_Full_Access (TASKS_TRIGGER_15);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_0  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_0);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_1  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_1);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_2  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_2);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_3  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_3);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_4  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_4);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_5  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_5);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_6  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_6);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_7  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_7);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_8  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_8);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_9  : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_9);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_10 : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_10);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_11 : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_11);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_12 : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_12);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_13 : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_13);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_14 : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_14);
      --  Description collection[n]: Event number n generated by triggering the
      --  corresponding TRIGGER[n] task
      EVENTS_TRIGGERED_15 : aliased EVENTS_TRIGGERED_Register;
      pragma Volatile_Full_Access (EVENTS_TRIGGERED_15);
      --  Enable or disable interrupt
      INTEN               : aliased INTEN_Register;
      pragma Volatile_Full_Access (INTEN);
      --  Enable interrupt
      INTENSET            : aliased INTENSET_Register;
      pragma Volatile_Full_Access (INTENSET);
      --  Disable interrupt
      INTENCLR            : aliased INTENCLR_Register;
      pragma Volatile_Full_Access (INTENCLR);
   end record
     with Volatile;

   for EGU_Peripheral use record
      TASKS_TRIGGER_0     at 16#0# range 0 .. 31;
      TASKS_TRIGGER_1     at 16#4# range 0 .. 31;
      TASKS_TRIGGER_2     at 16#8# range 0 .. 31;
      TASKS_TRIGGER_3     at 16#C# range 0 .. 31;
      TASKS_TRIGGER_4     at 16#10# range 0 .. 31;
      TASKS_TRIGGER_5     at 16#14# range 0 .. 31;
      TASKS_TRIGGER_6     at 16#18# range 0 .. 31;
      TASKS_TRIGGER_7     at 16#1C# range 0 .. 31;
      TASKS_TRIGGER_8     at 16#20# range 0 .. 31;
      TASKS_TRIGGER_9     at 16#24# range 0 .. 31;
      TASKS_TRIGGER_10    at 16#28# range 0 .. 31;
      TASKS_TRIGGER_11    at 16#2C# range 0 .. 31;
      TASKS_TRIGGER_12    at 16#30# range 0 .. 31;
      TASKS_TRIGGER_13    at 16#34# range 0 .. 31;
      TASKS_TRIGGER_14    at 16#38# range 0 .. 31;
      TASKS_TRIGGER_15    at 16#3C# range 0 .. 31;
      EVENTS_TRIGGERED_0  at 16#100# range 0 .. 31;
      EVENTS_TRIGGERED_1  at 16#104# range 0 .. 31;
      EVENTS_TRIGGERED_2  at 16#108# range 0 .. 31;
      EVENTS_TRIGGERED_3  at 16#10C# range 0 .. 31;
      EVENTS_TRIGGERED_4  at 16#110# range 0 .. 31;
      EVENTS_TRIGGERED_5  at 16#114# range 0 .. 31;
      EVENTS_TRIGGERED_6  at 16#118# range 0 .. 31;
      EVENTS_TRIGGERED_7  at 16#11C# range 0 .. 31;
      EVENTS_TRIGGERED_8  at 16#120# range 0 .. 31;
      EVENTS_TRIGGERED_9  at 16#124# range 0 .. 31;
      EVENTS_TRIGGERED_10 at 16#128# range 0 .. 31;
      EVENTS_TRIGGERED_11 at 16#12C# range 0 .. 31;
      EVENTS_TRIGGERED_12 at 16#130# range 0 .. 31;
      EVENTS_TRIGGERED_13 at 16#134# range 0 .. 31;
      EVENTS_TRIGGERED_14 at 16#138# range 0 .. 31;
      EVENTS_TRIGGERED_15 at 16#13C# range 0 .. 31;
      INTEN               at 16#300# range 0 .. 31;
      INTENSET            at 16#304# range 0 .. 31;
      INTENCLR            at 16#308# range 0 .. 31;
   end record;

   --  Event Generator Unit 0
   EGU0_Periph : aliased EGU_Peripheral
     with Import, Address => EGU0_Base;

   --  Event Generator Unit 1
   EGU1_Periph : aliased EGU_Peripheral
     with Import, Address => EGU1_Base;

   --  Event Generator Unit 2
   EGU2_Periph : aliased EGU_Peripheral
     with Import, Address => EGU2_Base;

   --  Event Generator Unit 3
   EGU3_Periph : aliased EGU_Peripheral
     with Import, Address => EGU3_Base;

   --  Event Generator Unit 4
   EGU4_Periph : aliased EGU_Peripheral
     with Import, Address => EGU4_Base;

   --  Event Generator Unit 5
   EGU5_Periph : aliased EGU_Peripheral
     with Import, Address => EGU5_Base;

end NRF52840.EGU;
