name = "ed_scan_nrf52840"
description = ""
version = "0.1.0-dev"

authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["ed_scan_nrf52840"]

[build-switches]
"*".ada_version = "Ada2022"
release.runtime_checks = "None"

[[depends-on]]
adabee_mlme = "*"
light_tasking_nrf52840 = "^15.4.0"

[[pins]]
adabee_mlme = { path = "../../../mac/mlme" }

[configuration.values]
adabee_phy.Driver = "nRF52840"
