name = "adabee_common"
description = "Common definitions for the AdaBee protocol stack"
version = "0.1.0-dev"

authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
