name = "rx_nrf52840"
description = "Example using the AdaBee PHY for packet reception on the nRF52840"
version = "0.1.0-dev"

authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["rx_nrf52840"]

[[depends-on]]
adabee_phy = "*"
light_tasking_nrf52840 = "^15.3.0"
gnatprove = "^15"

[[pins]]
adabee_phy = { path = "../../../phy" }
light_tasking_nrf52840 = { path = "/mnt/DATA/projects/ada/community-runtimes/install/light-tasking-nrf52840" }

[configuration.values]
adabee_phy.Driver = "nRF52840"
