--
--  Copyright 2026 (C) Daniel King
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--
with NRF52840.PPI;           use NRF52840.PPI;
with AdaBee.BSP.Conversions; use AdaBee.BSP.Conversions;

package body AdaBee.PHY.PPI_Scheduler is

   ----------------------------
   -- Peripheral Allocations --
   ----------------------------

   RTC_Periph : RTC_Peripheral renames
     AdaBee.BSP.Config.PPI_Scheduler_RTC_Periph;
   --  RTC peripheral to use as the main time base.

   TIMER_Periph : TIMER_Peripheral renames
     AdaBee.BSP.Config.PPI_Scheduler_TIMER_Periph;
   --  TIMER peripheral to use for high precision mode
   --
   --  Must be TIMER3 or TIMER4 since these have 6 CC channels. TIMERs 0, 1,
   --  and 2 only have 4 CC channels.

   TIMER_RTC_Sync_PPI_Channel : constant :=
     AdaBee.BSP.Config.PPI_Scheduler_PPI_CH_Idx;
   --  PPI channel used sync the TIMER with the RTC.

   ---------------------------------
   -- Peripheral Register Aliases --
   ---------------------------------

   --  The register definitions generated by svd2ada were generated with
   --  --no-vfa-on-types, which implies --no-arrays so some TIMER/RTC registers
   --  such as the CC registers are defined as CC_0, CC_1, CC_2, and so on
   --  instead of being defined as an array.
   --
   --  However, we want to be able to access them as an array, so we define
   --  our own versions of these structs.

   type RTC_CC_Register_VFA is new NRF52840.RTC.CC_Register
   with Volatile_Full_Access;

   subtype Bit_32 is UInt32 range 0 .. 1;

   RTC_Periph_CC : array (0 .. 3) of RTC_CC_Register_VFA
   with
     Volatile_Components,
     Size    => 4 * 32,
     Import,
     Address => RTC_Periph.CC_0'Address;

   RTC_Periph_EVENTS_COMPARE : array (0 .. 3) of Bit_32
   with
     Volatile_Components,
     Size    => 4 * 32,
     Import,
     Address => RTC_Periph.EVENTS_COMPARE_0'Address;

   TIMER_Periph_CC : array (0 .. 5) of NRF52840.UInt32
   with
     Volatile_Components,
     Size    => 6 * 32,
     Import,
     Address => TIMER_Periph.CC_0'Address;

   TIMER_Periph_TASKS_CAPTURE : array (0 .. 5) of Bit_32
   with
     Volatile_Components,
     Size    => 6 * 32,
     Import,
     Address => TIMER_Periph.TASKS_CAPTURE_0'Address;

   TIMER_Periph_EVENTS_COMPARE : array (0 .. 5) of Bit_32
   with
     Volatile_Components,
     Size    => 6 * 32,
     Import,
     Address => TIMER_Periph.EVENTS_COMPARE_0'Address;

   -------------------------
   -- RTC Characteristics --
   -------------------------

   RTC_Frequency : constant := 32_768;
   --  RTC frequency in Hz

   RTC_Overflow_Period : constant Time_Span :=
     Time_Span (2.0 ** 24) / RTC_Frequency;
   --  Amount of time it takes for the RTC to overflow (512 seconds with a
   --  24-bit counter running at 32.768 kHz).

   --------------------------
   -- TIMER Characteristics --
   --------------------------

   TIMER_Prescaler_Exponent : constant := 4;
   --  Prescaler exponent value to use for the TIMER.
   --
   --  fTIMER = 16 MHz / (2**PRESCALER)
   --
   --  A prescaler exponent of 4 sets a /16 prescaler, giving a 1 MHz timer

   TIMER_Frequency : constant := 16_000_000 / (2 ** TIMER_Prescaler_Exponent);
   --  TIMER frequency in Hz

   TIMER_Overflow_Period : constant Time_Span :=
     Time_Span (2.0 ** 32) / TIMER_Frequency;
   --  Amount of time it takes for the TIMER to overflow (a little over 1 hour
   --  and 11 minutes with a 32-bit counter running at 1 MHz).

   ---------------------------------
   -- Scheduler Timing Parameters --
   ---------------------------------

   Alarm_Guard_Time : constant Time_Span := 0.005;
   --  Alarms are scheduled into the TIMER or RTC peripheral this amount of
   --  time before the alarm's expiry time. This is a balance between timing
   --  accuracy of the alarm and setting the alarm early enough to
   --
   --  Once an alarm has been programmed into the TIMER/RTC (i.e. when the
   --  COMPARE value has been set) it cannot be changed without risking failure
   --  to trigger the PPI event at the desired time. Furthermore, the TIMER
   --  and RTC may have different clock sources, so the TIMER's sense of time
   --  might drift relative to the RTC's time (the "source of truth").
   --
   --  If we program the TIMER's COMPARE register too far in advance, then
   --  the TIMER and RTC might drift too much such that the alarm is triggered
   --  too early or late. If we program it too close to the trigger time, then
   --  we risk failing to program in time before the alarm time is reached
   --  (particularly if we're preempted by a higher-priority interrupt).
   --
   --  For example, if the relative error between the TIMER and RTC clocks is
   --  100 ppm, then the two will drift by 100 us per second. Programming the
   --  the TIMER 1 second before the alarm time would cause the alarm to be off
   --  by 100 us. Programming the TIMER 10 ms before, however, will result in
   --  an error of just 1 us.

   Max_Sleep : constant Time_Span := 1.0; --  RTC_Overflow_Period / 2.0;
   --  Maximum amount of time between periodic wakeups for time management

   function Needs_Scheduling (Alarm : Alarm_Data; Now : Time) return Boolean
   is (Alarm.Enabled
       and then not Alarm.Scheduled
       and then Time_Span (Alarm.Expiry_Time - Now) <= Alarm_Guard_Time);

   ---------------------------------------------
   -- RTC Capture/Compare Channel Allocations --
   ---------------------------------------------

   --  COMPARE channel 3 used for periodic wakeups to schedule alarms

   RTC_CC_Idx_Periodic_Wakeup : constant := 3;

   -----------------------------------------------
   -- TIMER Capture/Compare Channel Allocations --
   -----------------------------------------------

   --  Channel 5 used to calibrate the time difference between the RTC and the
   --  TIMER peripheral.

   TIMER_CC_RTC_Sync : constant := 5;

   --  Channel 4 used to capture the current value of the timer's counter.
   --
   --  This is needed since the TIMER peripheral doesn't provide a dedicated
   --  COUNTER register, so we need to use one of the CC channels to capture
   --  the time.

   TIMER_CC_Idx_Counter_Capture : constant := 4;

   --  Channels 0 .. 3 are used for the alarms

   --------------------------
   -- Conversion Utilities --
   --------------------------

   function RTC_Time_Span (Ticks : UInt24) return Time_Span
   is (Time_Span (Ticks) / RTC_Frequency)
   with
     Post =>
       RTC_Time_Span'Result >= 0.0
       and then RTC_Time_Span'Result < RTC_Overflow_Period;
   --  Convert a quantity of RTC ticks to a Time_Span.
   --
   --  1 RTC tick is equal to 30.517_578_125 microseconds.

   function TIMER_Time_Span (Ticks : UInt32) return Time_Span
   is (Time_Span (Ticks) / TIMER_Frequency)
   with
     Post =>
       TIMER_Time_Span'Result >= 0.0
       and then TIMER_Time_Span'Result < TIMER_Overflow_Period;
   --  Convert a quantity of TIMER ticks to a Time_Span.
   --
   --  1 TIMER tick is equal to 1 microsecond.

   function To_TIMER_Ticks (T : Time_Span) return UInt32
   is (UInt32 (T * TIMER_Frequency))
   with Pre => T >= 0.0 and then T < TIMER_Overflow_Period;

   function To_RTC_Ticks (T : Time_Span) return UInt24
   is (UInt24 (T * RTC_Frequency))
   with Pre => T >= 0.0 and then T < RTC_Overflow_Period;

   ---------------
   -- Scheduler --
   ---------------

   protected body Scheduler is

      -----------
      -- Start --
      -----------

      procedure Start is
      begin
         if not Started then
            Started := True;

            RTC_Time_Hi := 0.0;

            --  Set 32.768 kHz frequency.
            --
            --  fCOUNTER = 32768 / (PRESCALER+1)

            RTC_Periph.PRESCALER :=
              (PRESCALER => UInt12 ((32_768 / RTC_Frequency) - 1),
               others    => <>);

            --  Enable the interrupt for periodic wakeups for housekeeping

            RTC_Periph.INTENSET :=
              (COMPARE =>
                 (As_Array => True,
                  Arr      =>
                    (RTC_CC_Idx_Periodic_Wakeup => Set, others => <>)),
               others  => <>);

            --  Need the OVRFLW event to detect counter wrap-around

            RTC_Periph.EVTENSET := (OVRFLW => Set, others => <>);

            --  Clear and start the timer

            RTC_Periph.TASKS_CLEAR := (TASKS_CLEAR => 1, others => <>);
            RTC_Periph.TASKS_START := (TASKS_START => 1, others => <>);

            Schedule_Next_Wakeup;
         end if;
      end Start;

      ----------
      -- Stop --
      ----------

      procedure Stop is
      begin
         if Started then
            if Current_Mode = High_Precision then
               Enter_Low_Power_Mode; --  Turn off the TIMER

            end if;

            RTC_Periph.TASKS_STOP := (TASKS_STOP => 1, others => <>);

            for Channel in LP_Channel_Number loop
               Cancel_Low_Power_Alarm (Channel);
            end loop;

            for Channel in HP_Channel_Number loop
               Cancel_High_Precision_Alarm (Channel);
            end loop;

            Started := False;
         end if;
      end Stop;

      ----------------
      -- Read_Clock --
      ----------------

      procedure Read_Clock (Now : out AdaBee.Time_Units.Time) is
         Unused : UInt32;
      begin
         if Current_Mode = Low_Power then
            Read_RTC_Time (Now);
         else
            Read_TIMER_Time (Now, Unused);

            pragma Unreferenced (Unused);
         end if;
      end Read_Clock;

      ----------
      -- Mode --
      ----------

      function Mode return Mode_Type
      is (Current_Mode);

      --------------
      -- Set_Mode --
      --------------

      procedure Set_Mode (New_Mode : Mode_Type) is
      begin
         if Started then
            if New_Mode /= Current_Mode then

               Current_Mode := New_Mode;

               case New_Mode is
                  when Low_Power      =>
                     Enter_Low_Power_Mode;

                  when High_Precision =>
                     Enter_High_Precision_Mode;
               end case;
            end if;
         end if;
      end Set_Mode;

      ---------------------
      -- Prepare_Capture --
      ---------------------

      procedure Prepare_Capture (Channel : HP_Channel_Number; TEP : out UInt32)
      is
         Addr : System.Address;

      begin
         Cancel_High_Precision_Alarm (Channel);

         case Channel is
            when 0 =>
               Addr := TIMER_Periph.TASKS_CAPTURE_0'Address;

            when 1 =>
               Addr := TIMER_Periph.TASKS_CAPTURE_1'Address;

            when 2 =>
               Addr := TIMER_Periph.TASKS_CAPTURE_2'Address;

            when 3 =>
               Addr := TIMER_Periph.TASKS_CAPTURE_3'Address;
         end case;

         TEP := To_UInt32 (Addr);
      end Prepare_Capture;

      ---------------------------
      -- Get_Capture_Timestamp --
      ---------------------------

      procedure Get_Capture_Timestamp
        (Channel : HP_Channel_Number; Timestamp : out Time)
      is
         CC_Ticks        : constant UInt32 := TIMER_Periph_CC (Channel);
         Sync_Time_Ticks : UInt32;
         Now_Ticks       : UInt32;
      begin
         --  Get what the TIMER time was at the last RTC sync event

         Get_TIMER_Sync_Time (Sync_Time_Ticks, Timestamp);

         --  Adjust the timestamp based on how many ticks elapsed between the
         --  CAPTURE time and the last RTC sync time.
         --
         --  Note that the CAPTURE event can occur before or after the last
         --  RTC sync event, and that the TIMER's counter might also have
         --  overflowed between the two events. This makes it difficult to
         --  calculate the time elapsed between the two. But since both events
         --  occurred before the current time, we can use that to derive the
         --  actual time of the CAPTURE event relative to the last RTC sync.

         Read_TIMER_COUNTER (Now_Ticks);

         Timestamp :=
           Timestamp
           + TIMER_Time_Span (Now_Ticks - Sync_Time_Ticks)
           - TIMER_Time_Span (Now_Ticks - CC_Ticks);

         --  Prevent returning a negative time
         --
         --  This can occur if the TIMER's clock is faster than the RTC clock
         --  and enough time has elapsed between the CAPTURE event and calling
         --  this procedure such that the clocks have drifted enough to cause
         --  a negative apparent time.

         Timestamp := Time'Base'Max (Timestamp, 0.0);
      end Get_Capture_Timestamp;

      -------------------------
      -- Set_Low_Power_Alarm --
      -------------------------

      procedure Set_Low_Power_Alarm
        (Channel         : LP_Channel_Number;
         Trigger_At      : Time;
         EEP_Address     : System.Address;
         Already_Expired : out Boolean)
      is
         Now : Time;

      begin
         --  Cancel any previously pending alarm

         Cancel_Low_Power_Alarm (Channel);

         --  Get the current time so we can check if the alarm time has already
         --  been reached.

         Read_RTC_Time (Now);

         if Trigger_At <= Now then
            Already_Expired := True;

         else
            --  Alarm is in the future and in the correct mode

            Already_Expired := False;

            LP_Alarms (Channel) :=
              (Expiry_Time => Trigger_At,
               Enabled     => True,
               Scheduled   => False,
               EEP_Address => EEP_Address);

            --  If the alarm time is in the near future then schedule it now,
            --  otherwise schedule a wakeup shortly before the alarm expires.

            if Time_Span (Trigger_At - Now) > Alarm_Guard_Time then
               Schedule_Next_Wakeup;

            else
               --  Alarm time is in the near future. Schedule it now

               Schedule_Low_Power_Alarm (Channel);

               --  Check if the alarm time has been reached, but the event
               --  was not triggered. This indicates that the alarm time was
               --  reached while the timer was being configured.

               Read_RTC_Time (Now);

               if Now >= Trigger_At
                 and then RTC_Periph_EVENTS_COMPARE (Channel) = 0
               then
                  Already_Expired := True;
                  Cancel_Low_Power_Alarm (Channel);
               end if;
            end if;
         end if;
      end Set_Low_Power_Alarm;

      ------------------------------
      -- Set_High_Precision_Alarm --
      ------------------------------

      procedure Set_High_Precision_Alarm
        (Channel         : HP_Channel_Number;
         Trigger_At      : Time;
         EEP_Address     : System.Address;
         Already_Expired : out Boolean)
      is
         Now             : Time;
         Now_TIMER_Ticks : UInt32;

      begin
         --  Cancel any previously pending alarm

         Cancel_High_Precision_Alarm (Channel);

         --  Get the current time so we can check if the alarm time has already
         --  been reached.

         Read_TIMER_Time (Now, Now_TIMER_Ticks);

         if Trigger_At <= Now then
            Already_Expired := True;

         elsif Current_Mode = Low_Power then
            --  Cannot set a high-precision timer when in low power mode
            --  since this requires the TIMER to be enabled, which is off
            --  in low-power mode.

            Already_Expired := True;

         else
            --  Alarm is in the future and in the correct mode

            Already_Expired := False;

            HP_Alarms (Channel) :=
              (Expiry_Time => Trigger_At,
               Enabled     => True,
               Scheduled   => False,
               EEP_Address => EEP_Address);

            --  If the alarm time is in the near future then schedule it now,
            --  otherwise schedule a wakeup shortly before the alarm expires.

            if Time_Span (Trigger_At - Now) > Alarm_Guard_Time then
               Schedule_Next_Wakeup;

            else
               --  Alarm time is in the near future. Schedule it now

               Schedule_High_Precision_Alarm (Channel, Now, Now_TIMER_Ticks);

               --  Check if the alarm time has been reached, but the event
               --  was not triggered. This indicates that the alarm time was
               --  reached while the timer was being configured.

               Read_TIMER_Time (Now, Now_TIMER_Ticks);

               if Now >= Trigger_At
                 and then TIMER_Periph_EVENTS_COMPARE (Channel) = 0
               then
                  Already_Expired := True;
                  Cancel_High_Precision_Alarm (Channel);
               end if;
            end if;
         end if;

      end Set_High_Precision_Alarm;

      ----------------------------
      -- Cancel_Low_Power_Alarm --
      ----------------------------

      procedure Cancel_Low_Power_Alarm (Channel : LP_Channel_Number) is
      begin
         if LP_Alarms (Channel).Enabled then

            if LP_Alarms (Channel).Scheduled then

               --  Disconnect the event from the PPI channel by clearing the
               --  PPI channel's Event Endpoint (EEP) register.

               declare
                  EEP : UInt32
                  with
                    Volatile,
                    Import,
                    Address => LP_Alarms (Channel).EEP_Address;
               begin
                  EEP := 0;
               end;

               --  Disable the RTC's COMPARE interrupt

               declare
                  INTENCLR : NRF52840.RTC.INTENCLR_Register;
                  EVTENCLR : NRF52840.RTC.EVTENCLR_Register;
               begin
                  INTENCLR := (others => <>);
                  INTENCLR.COMPARE.Arr (Channel) := Clear;
                  RTC_Periph.INTENCLR := INTENCLR;

                  EVTENCLR := (others => <>);
                  EVTENCLR.COMPARE.Arr (Channel) := Clear;
                  RTC_Periph.EVTENCLR := EVTENCLR;
               end;
            end if;

            LP_Alarms (Channel) := (others => <>);
         end if;
      end Cancel_Low_Power_Alarm;

      ---------------------------------
      -- Cancel_High_Precision_Alarm --
      ---------------------------------

      procedure Cancel_High_Precision_Alarm (Channel : HP_Channel_Number) is
      begin
         if HP_Alarms (Channel).Enabled then

            if HP_Alarms (Channel).Scheduled then

               --  Disconnect the event from the PPI channel by clearing the
               --  PPI channel's Event Endpoint (EEP) register.

               declare
                  EEP : UInt32
                  with
                    Volatile,
                    Import,
                    Address => HP_Alarms (Channel).EEP_Address;
               begin
                  EEP := 0;
               end;

               --  Disable the TIMER's COMPARE interrupt

               declare
                  INTENCLR : NRF52840.TIMER.INTENCLR_Register;
               begin
                  INTENCLR := (others => <>);
                  INTENCLR.COMPARE.Arr (Channel) := Clear;
                  TIMER_Periph.INTENCLR := INTENCLR;
               end;
            end if;

            HP_Alarms (Channel) := (others => <>);
         end if;
      end Cancel_High_Precision_Alarm;

      ----------------------
      -- Read_RTC_Counter --
      ----------------------

      procedure Read_RTC_Counter (Counter : out UInt24) is
      begin
         Counter := RTC_Periph.COUNTER.COUNTER;

         --  Check if the counter overflowed

         while RTC_Periph.EVENTS_OVRFLW.EVENTS_OVRFLW /= 0 loop

            --  Clear event
            RTC_Periph.EVENTS_OVRFLW := (EVENTS_OVRFLW => 0, others => <>);

            --  Need to capture the timer again
            Counter := RTC_Periph.COUNTER.COUNTER;

            --  New RTC period has started
            RTC_Time_Hi := RTC_Time_Hi + RTC_Overflow_Period;
         end loop;
      end Read_RTC_Counter;

      -------------------
      -- Read_RTC_Time --
      -------------------

      procedure Read_RTC_Time (Now : out AdaBee.Time_Units.Time) is
         Ticks : UInt24;
      begin
         Read_RTC_Counter (Ticks);
         Now := RTC_Time_Hi + RTC_Time_Span (Ticks);
      end Read_RTC_Time;

      -------------------------
      -- Get_TIMER_Sync_Time --
      -------------------------

      procedure Get_TIMER_Sync_Time
        (Sync_Time_Ticks : out UInt32; Sync_Time : out Time)
      is
         RTC_Ticks : UInt24;

      begin

         --  One of the TIMER's CAPTURE channels is connected to the RTC's
         --  EVENTS_TICK event so we can capture the value of the TIMER's
         --  COUNTER on every RTC tick (every ~30.5 us).
         --
         --  Once we know what value the two counters had at the same time,
         --  we can calculate what the RTC time was at that event.

         --  Read the COUNTER and CC registers without a TICK event
         --  occurring in the middle.

         loop
            RTC_Periph.EVENTS_TICK := (EVENTS_TICK => 0, others => <>);
            RTC_Ticks := RTC_Periph.COUNTER.COUNTER;
            Sync_Time_Ticks := TIMER_Periph_CC (TIMER_CC_RTC_Sync);

            exit when RTC_Periph.EVENTS_TICK = (0, 0);
         end loop;

         --  Check if the RTC overflowed

         while RTC_Periph.EVENTS_OVRFLW.EVENTS_OVRFLW /= 0 loop

            --  Clear the event

            RTC_Periph.EVENTS_OVRFLW := (EVENTS_OVRFLW => 0, others => <>);

            --  Need to capture the timer again

            loop
               RTC_Periph.EVENTS_TICK := (EVENTS_TICK => 0, others => <>);
               RTC_Ticks := RTC_Periph.COUNTER.COUNTER;
               Sync_Time_Ticks := TIMER_Periph_CC (TIMER_CC_RTC_Sync);

               exit when RTC_Periph.EVENTS_TICK = (0, 0);
            end loop;

            --  New RTC period has started

            RTC_Time_Hi := RTC_Time_Hi + RTC_Overflow_Period;
         end loop;

         --  Calculate what the time was at the last sync event

         Sync_Time := RTC_Time_Hi + RTC_Time_Span (RTC_Ticks);
      end Get_TIMER_Sync_Time;

      ---------------------
      -- Read_TIMER_Time --
      ---------------------

      procedure Read_TIMER_Time
        (Now : out AdaBee.Time_Units.Time; Now_Ticks : out UInt32)
      is
         Sync_Time_Ticks : UInt32;

      begin
         --  Get what the time was at the last sync event with the RTC

         Get_TIMER_Sync_Time (Sync_Time_Ticks, Now);

         --  Adjust based on how many ticks have elapsed since then

         Read_TIMER_COUNTER (Now_Ticks);

         Now := Now + TIMER_Time_Span (Now_Ticks - Sync_Time_Ticks);
      end Read_TIMER_Time;

      ------------------------
      -- Read_TIMER_COUNTER --
      ------------------------

      procedure Read_TIMER_COUNTER (Counter : out UInt32) is
      begin
         TIMER_Periph_TASKS_CAPTURE (TIMER_CC_Idx_Counter_Capture) := 1;
         Counter := TIMER_Periph_CC (TIMER_CC_Idx_Counter_Capture);
      end Read_TIMER_COUNTER;

      --------------------------
      -- Enter_Low_Power_Mode --
      --------------------------

      procedure Enter_Low_Power_Mode is
      begin
         --  Turn off the TIMER
         --
         --  Errata 78: TIMER: High current consumption when using timer STOP
         --  task only.
         --
         --  Workaround: Use the SHUTDOWN task after the STOP task or instead
         --  of the STOP task

         TIMER_Periph.TASKS_SHUTDOWN := (TASKS_SHUTDOWN => 1, others => <>);
         --  Disable EVENTS_TICK to save some power

         RTC_Periph.EVTENCLR := (TICK => Clear, others => <>);

         --  Disable the PPI channel used to sync the RTC and TIMER

         PPI_Periph.CHENCLR :=
           (As_Array => True,
            Arr      =>
              (TIMER_RTC_Sync_PPI_Channel => Clear,
               others                     => CHENCLR_CH0_Field_Reset));

         --  Cancel all high precision alarms

         for Channel in HP_Channel_Number loop
            Cancel_High_Precision_Alarm (Channel);
         end loop;
      end Enter_Low_Power_Mode;

      -------------------------------
      -- Enter_High_Precision_Mode --
      -------------------------------

      procedure Enter_High_Precision_Mode is
         Unused : UInt32;

      begin
         --  Ensure that the timer is stopped and cleared

         TIMER_Periph.TASKS_SHUTDOWN := (TASKS_SHUTDOWN => 1, others => <>);
         TIMER_Periph.TASKS_CLEAR := (TASKS_CLEAR => 1, others => <>);
         TIMER_Periph.CC_0 := 0;
         TIMER_Periph.CC_1 := 0;
         TIMER_Periph.CC_2 := 0;
         TIMER_Periph.CC_3 := 0;
         TIMER_Periph.CC_4 := 0;
         TIMER_Periph.CC_5 := 0;

         --  Configure the TIMER

         TIMER_Periph.PRESCALER :=
           (PRESCALER => TIMER_Prescaler_Exponent, others => <>);
         TIMER_Periph.MODE := (MODE => NRF52840.TIMER.Timer, others => <>);
         TIMER_Periph.BITMODE := (BITMODE => Val_32Bit, others => <>);

         --  Connect RTC.EVENTS_TICK to TIMER.TASKS_CAPTURE via the PPI

         PPI_Periph.CH (TIMER_RTC_Sync_PPI_Channel).EEP :=
           To_UInt32 (RTC_Periph.EVENTS_TICK'Address);

         PPI_Periph.CH (TIMER_RTC_Sync_PPI_Channel).TEP :=
           To_UInt32 (TIMER_Periph_TASKS_CAPTURE (TIMER_CC_RTC_Sync)'Address);

         --  Enable the PPI channel

         PPI_Periph.CHENSET :=
           (As_Array => True,
            Arr      =>
              (TIMER_RTC_Sync_PPI_Channel => Set,
               others                     => CHENSET_CH0_Field_Reset));

         --  Enable the RTC TICK event

         RTC_Periph.EVENTS_TICK := (EVENTS_TICK => 0, others => <>);
         RTC_Periph.EVTENSET := (TICK => Set, others => <>);

         --  Start the TIMER

         TIMER_Periph.TASKS_START := (TASKS_START => 1, others => <>);
      end Enter_High_Precision_Mode;

      -----------------------------------
      -- Schedule_High_Precision_Alarm --
      -----------------------------------

      procedure Schedule_High_Precision_Alarm
        (Channel : HP_Channel_Number; Now : Time; Now_Ticks : UInt32)
      is
         INTENSET      : NRF52840.TIMER.INTENSET_Register;
         Alarm         : Alarm_Data renames HP_Alarms (Channel);
         Time_To_Alarm : Time_Span;

      begin
         Alarm.Scheduled := True;

         --  Set the COMPARE register to the timer's current time to prevent
         --  a spurious COMPARE event if the old COMPARE value happens to be
         --  reached while we're setting everything up.

         TIMER_Periph_TASKS_CAPTURE (TIMER_CC_Idx_Counter_Capture) := 1;

         TIMER_Periph_CC (Channel) :=
           TIMER_Periph_CC (TIMER_CC_Idx_Counter_Capture);

         --  Clear any previous COMPARE event so that we can detect if the
         --  event triggered later on.

         TIMER_Periph_EVENTS_COMPARE (Channel) := 0;

         --  Generate an interrupt when the alarm triggers so that we can clean
         --  up the alarm when it's done.

         INTENSET := (others => <>);
         INTENSET.COMPARE.Arr (Channel) := Set;
         TIMER_Periph.INTENSET := INTENSET;

         --  Hook up the PPI channel to the timer's EVENTS_CAPTURE so that the
         --  PPI will be triggered when the time is reached.

         declare
            EEP : UInt32
            with Volatile, Import, Address => Alarm.EEP_Address;
         begin
            EEP := To_UInt32 (TIMER_Periph_EVENTS_COMPARE (Channel)'Address);
         end;

         --  Configure the COMPARE register with the desired trigger time
         --
         --  Note that the current time (now) might be right before the TIMER
         --  overflows and the desired alarm time is right at the start of the
         --  next TIMER period. In this case we need to subtract one period
         --  so that we have an offset relative to the start of whichever
         --  period the alarm time is in.
         --
         --           overflow
         --            period
         --        v---------------v
         --        |---------------|---------------|
         --        ^             ^   ^
         --        |             |   |
         --  TIMER_Time_Hi     Now   Alarm Time

         Time_To_Alarm := Time_Span (Alarm.Expiry_Time - Now);

         if Time_To_Alarm >= 0.0 then
            TIMER_Periph_CC (Channel) :=
              Now_Ticks + To_TIMER_Ticks (Time_To_Alarm);
         end if;
      end Schedule_High_Precision_Alarm;

      ------------------------------
      -- Schedule_Low_Power_Alarm --
      ------------------------------

      procedure Schedule_Low_Power_Alarm (Channel : LP_Channel_Number) is
         RTC_Tick_Period : constant Time_Span := 30.0e-6;

         INTENSET      : NRF52840.RTC.INTENSET_Register;
         EVTENSET      : NRF52840.RTC.EVTENSET_Register;
         Alarm         : Alarm_Data renames LP_Alarms (Channel);
         Period_Offset : Time_Span;

      begin
         Alarm.Scheduled := True;

         --  Set the COMPARE register to the timer's current time to prevent
         --  a spurious COMPARE event if the old COMPARE value happens to be
         --  reached while we're setting everything

         RTC_Periph_CC (Channel) :=
           (COMPARE => RTC_Periph.COUNTER.COUNTER, others => <>);

         --  Clear any previous COMPARE event so that we can detect if the
         --  event triggered later on.

         RTC_Periph_EVENTS_COMPARE (Channel) := 0;

         --  Generate an interrupt when the alarm triggers so that we can clean
         --  up the alarm when it's done.

         INTENSET := (others => <>);
         INTENSET.COMPARE.Arr (Channel) := Set;
         RTC_Periph.INTENSET := INTENSET;

         EVTENSET := (others => <>);
         EVTENSET.COMPARE.Arr (Channel) := Set;
         RTC_Periph.EVTENSET := EVTENSET;

         --  Hook up the PPI channel to the timer's EVENTS_CAPTURE so that the
         --  PPI will be triggered when the time is reached.

         declare
            EEP : UInt32
            with Volatile, Import, Address => Alarm.EEP_Address;
         begin
            EEP := To_UInt32 (RTC_Periph_EVENTS_COMPARE (Channel)'Address);
         end;

         --  Configure the COMPARE register with the desired trigger time
         --
         --  Note that the current time (now) might be right before the RTC
         --  overflows and the desired alarm time is right at the start of the
         --  next RTC period. In this case we need to subtract one period
         --  so that we have an offset relative to the start of whichever
         --  period the alarm time is in.
         --
         --         overflow
         --          period
         --      v---------------v
         --      |---------------|---------------|
         --      ^             ^   ^
         --      |             |   |
         --  RTC_Time_Hi     Now   Alarm Time

         Period_Offset :=
           Time_Span (Alarm.Expiry_Time - RTC_Time_Hi)
           + RTC_Tick_Period; --  Round up when convert to ticks

         if Period_Offset >= RTC_Overflow_Period then
            Period_Offset := Period_Offset - RTC_Overflow_Period;
         end if;

         RTC_Periph_CC (Channel) :=
           (COMPARE => To_RTC_Ticks (Period_Offset), others => <>);
      end Schedule_Low_Power_Alarm;

      -------------------------
      -- Earliest_Alarm_Time --
      -------------------------

      function Earliest_Alarm_Time (Include_Scheduled : Boolean) return Time is
         Earliest_Time : Time := Time'Last;

      begin
         for Alarm of LP_Alarms loop
            if Alarm.Enabled
              and then (Include_Scheduled or else not Alarm.Scheduled)
              and then Alarm.Expiry_Time < Earliest_Time
            then
               Earliest_Time := Alarm.Expiry_Time;
            end if;
         end loop;

         for Alarm of HP_Alarms loop
            if Alarm.Enabled
              and then (Include_Scheduled or else not Alarm.Scheduled)
              and then Alarm.Expiry_Time < Earliest_Time
            then
               Earliest_Time := Alarm.Expiry_Time;
            end if;
         end loop;

         return Earliest_Time;
      end Earliest_Alarm_Time;

      --------------------------
      -- Schedule_Next_Wakeup --
      --------------------------

      procedure Schedule_Next_Wakeup is
         Earliest : Time;
         Now      : Time;
         Ticks    : UInt24;

         Sleep_Span  : Time_Span;
         Sleep_Ticks : UInt24;

      begin
         --  Determine when to next wake up.
         --
         --  We wake up either shortly in advance of the next alarm
         --  (so that we have time to schedule it), or periodically within
         --  each RTC overflow period for regular housekeeping.

         Earliest := Earliest_Alarm_Time (Include_Scheduled => False);

         Read_RTC_Counter (Ticks);
         Now := RTC_Time_Hi + RTC_Time_Span (Ticks);

         Sleep_Span :=
           Time_Span'Min
             (Time_Span (Earliest - Now) - Alarm_Guard_Time, Max_Sleep);

         --  Prevent negative values

         Sleep_Span := Time_Span'Max (Sleep_Span, 0.0);

         pragma Assert (Sleep_Span > 0.0);
         pragma Assert (Sleep_Span < RTC_Overflow_Period);

         Sleep_Ticks := To_RTC_Ticks (Sleep_Span);

         --  If the RTC COUNTER is currently N, then we need to set CC to at
         --  least N+2 to guarantee that it will trigger at the correct time.
         --
         --  See Section 6.22.7 of nRF52840 PS v1.11

         Sleep_Ticks := UInt24'Max (Sleep_Ticks, 2);

         --  Schedule the COMPARE

         RTC_Periph_CC (RTC_CC_Idx_Periodic_Wakeup) :=
           (COMPARE => Ticks + Sleep_Ticks, others => <>);

      end Schedule_Next_Wakeup;

      ---------------------------
      -- RTC_Interrupt_Handler --
      ---------------------------

      procedure RTC_Interrupt_Handler is
         Now             : Time;
         Now_TIMER_Ticks : UInt32;
      begin
         --  Clear the COMPARE channel used for the periodic wakeups

         RTC_Periph_EVENTS_COMPARE (RTC_CC_Idx_Periodic_Wakeup) := 0;

         if Current_Mode = Low_Power then
            Read_RTC_Time (Now);

         else
            Read_TIMER_Time (Now, Now_TIMER_Ticks);

            --  Schedule any high precision alarms that are expiring soon

            for Channel in HP_Channel_Number loop
               if Needs_Scheduling (HP_Alarms (Channel), Now) then
                  Schedule_High_Precision_Alarm
                    (Channel, Now, Now_TIMER_Ticks);
               end if;
            end loop;

         end if;

         --  Schedule any low power alarms that are expiring soon

         for Channel in LP_Channel_Number loop
            if Needs_Scheduling (LP_Alarms (Channel), Now) then
               Schedule_Low_Power_Alarm (Channel);
            end if;
         end loop;

         --  Clean up any expired low power alarms

         for Channel in LP_Channel_Number loop
            if RTC_Periph_EVENTS_COMPARE (Channel) /= 0 then

               RTC_Periph_EVENTS_COMPARE (Channel) := 0;

               if LP_Alarms (Channel).Scheduled then
                  Cancel_Low_Power_Alarm (Channel);
               end if;
            end if;
         end loop;

         Schedule_Next_Wakeup;
      end RTC_Interrupt_Handler;

      -----------------------------
      -- TIMER_Interrupt_Handler --
      -----------------------------

      procedure TIMER_Interrupt_Handler is
         Unused : UInt32;

      begin

         --  Clean up any expired high precision alarms

         for Channel in HP_Channel_Number loop
            if TIMER_Periph_EVENTS_COMPARE (Channel) /= 0 then

               TIMER_Periph_EVENTS_COMPARE (Channel) := 0;

               if HP_Alarms (Channel).Scheduled then
                  Cancel_High_Precision_Alarm (Channel);
               end if;
            end if;
         end loop;
      end TIMER_Interrupt_Handler;

   end Scheduler;

end AdaBee.PHY.PPI_Scheduler;
